version: "3.1"
services:
  install:
    image: node:18
    user: node
    volumes:
      - .:/data
    command: bash -c "cd /data && rm -rf node_modules && rm -f package-lock.json && npm i"
  update:
    image: node:18
    user: node
    volumes:
      - .:/data
    command: bash -c "cd /data && npm update"     
  deploy:
    image: node:18
    user: node
    volumes:
      - .:/data
    command: bash -c "cd /data && npm run deploy"    
  deployer:
    image: node:18
    user: node
    volumes:
      - .:/data
    ports:
      - 8011:8080
    command: bash -c "cd /data && npm run deployer"      
  setup:
    image: node:18
    user: node
    volumes:
      - .:/data
    command: bash -c "cd /data && npm run setup"        
  build:
    image: node:18
    user: node
    volumes:
      - .:/data
    command: bash -c "cd /data && npm run build"
  test:
    image: node:18
    user: node
    volumes:
      - .:/data
    command: bash -c "cd /data && npm run test"      